package com.levi.web.model;

public class Borrow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow.id
     *
     * @mbg.generated Sat Mar 28 14:18:29 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow.username
     *
     * @mbg.generated Sat Mar 28 14:18:29 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow.book
     *
     * @mbg.generated Sat Mar 28 14:18:29 CST 2020
     */
    private String book;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow.id
     *
     * @return the value of borrow.id
     *
     * @mbg.generated Sat Mar 28 14:18:29 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow.id
     *
     * @param id the value for borrow.id
     *
     * @mbg.generated Sat Mar 28 14:18:29 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow.username
     *
     * @return the value of borrow.username
     *
     * @mbg.generated Sat Mar 28 14:18:29 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow.username
     *
     * @param username the value for borrow.username
     *
     * @mbg.generated Sat Mar 28 14:18:29 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow.book
     *
     * @return the value of borrow.book
     *
     * @mbg.generated Sat Mar 28 14:18:29 CST 2020
     */
    public String getBook() {
        return book;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow.book
     *
     * @param book the value for borrow.book
     *
     * @mbg.generated Sat Mar 28 14:18:29 CST 2020
     */
    public void setBook(String book) {
        this.book = book == null ? null : book.trim();
    }
}